"""post-drop-person autogen

Revision ID: 0f8d7d07c6ca
Revises: 7f909e543305
Create Date: 2025-10-12 04:49:43.608099

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0f8d7d07c6ca'
down_revision = '7f909e543305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First remove FK and column on phonenumber that depend on person
    try:
        op.drop_constraint(op.f('phonenumber_person_id_fkey'), 'phonenumber', type_='foreignkey')
    except Exception:
        pass
    try:
        op.drop_column('phonenumber', 'person_id')
    except Exception:
        pass
    # Then drop person table and its indexes
    try:
        op.drop_index(op.f('ix_person_email'), table_name='person')
    except Exception:
        pass
    try:
        op.drop_table('person')
    except Exception:
        pass
    # Add new phonenumber columns (nullable to avoid migration issues)
    op.add_column('phonenumber', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('phonenumber', sa.Column('more_info', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('phonenumber', sa.Column('owner_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('phonenumber', sa.Column('owner_id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phonenumber', sa.Column('person_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('phonenumber_person_id_fkey'), 'phonenumber', 'person', ['person_id'], ['id'])
    op.drop_column('phonenumber', 'owner_id')
    op.drop_column('phonenumber', 'owner_type')
    op.drop_column('phonenumber', 'more_info')
    op.drop_column('phonenumber', 'is_verified')
    op.create_table('person',
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('day_of_birth', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('month_of_birth', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('year_of_birth', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('person_pkey'))
    )
    op.create_index(op.f('ix_person_email'), 'person', ['email'], unique=True)
    # ### end Alembic commands ###
