"""Updated travel agency roles

Revision ID: 25990eb36765
Revises: 621234stayts
Create Date: 2025-10-21 02:15:49.544484

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '25990eb36765'
down_revision = '621234stayts'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Create the enum type if it doesn't already exist
    staffrole_enum = sa.Enum('AGENT', 'MANAGER', 'SUPPORT', 'OWNER', name='staffrole')
    staffrole_enum.create(op.get_bind(), checkfirst=True)

    # Alter the column to use the newly created enum type with a USING clause for casting
    op.alter_column('travelagencystaff', 'role',
                    existing_type=sa.VARCHAR(),
                    type_=staffrole_enum,
                    existing_nullable=True,
                    postgresql_using="role::staffrole")
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert column to its original VARCHAR type
    op.alter_column('travelagencystaff', 'role',
                    existing_type=sa.Enum('AGENT', 'MANAGER', 'SUPPORT', 'OWNER', name='staffrole'),
                    type_=sa.VARCHAR(),
                    existing_nullable=True)

    # Drop the enum type after downgrading
    sa.Enum('AGENT', 'MANAGER', 'SUPPORT', name='staffrole').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
