"""made the contact_email mandatory for travel_agency

Revision ID: 26238344a724
Revises: a92de890751c
Create Date: 2026-02-12 05:51:36.617244

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '26238344a724'
down_revision = 'a92de890751c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('travelagency', 'contact_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('travelagency', 'contact_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
