"""Removed first level travel_id from booking table

Revision ID: 2697aac7e31f
Revises: 85b963180f9a
Create Date: 2026-05-21 05:46:26.728941

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2697aac7e31f'
down_revision = '85b963180f9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('booking_traveler_id_fkey'), 'booking', type_='foreignkey')
    op.drop_column('booking', 'traveler_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('traveler_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('booking_traveler_id_fkey'), 'booking', 'profile', ['traveler_id'], ['id'])
    # ### end Alembic commands ###
