"""Made stayunit_id for BookingStay optional

Revision ID: 2e37a9d4b163
Revises: e8e409979e48
Create Date: 2026-05-24 19:16:06.357779

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2e37a9d4b163'
down_revision = 'e8e409979e48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookingstay', 'stayunit_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookingstay', 'stayunit_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
