"""Updated profile table

Revision ID: 320b1617bac3
Revises: 32818e172698
Create Date: 2025-10-23 17:40:46.294707

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '320b1617bac3'
down_revision = '32818e172698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('primary_phone_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('profile', sa.Column('secondary_phone_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('profile', sa.Column('primary_email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('profile', sa.Column('secondary_email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('profile', sa.Column('created_by_user_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_profile_primary_email'), 'profile', ['primary_email'], unique=True)
    op.create_index(op.f('ix_profile_primary_phone_number'), 'profile', ['primary_phone_number'], unique=True)
    op.create_index(op.f('ix_profile_secondary_email'), 'profile', ['secondary_email'], unique=True)
    op.create_index(op.f('ix_profile_secondary_phone_number'), 'profile', ['secondary_phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_secondary_phone_number'), table_name='profile')
    op.drop_index(op.f('ix_profile_secondary_email'), table_name='profile')
    op.drop_index(op.f('ix_profile_primary_phone_number'), table_name='profile')
    op.drop_index(op.f('ix_profile_primary_email'), table_name='profile')
    op.drop_column('profile', 'created_by_user_id')
    op.drop_column('profile', 'secondary_email')
    op.drop_column('profile', 'primary_email')
    op.drop_column('profile', 'secondary_phone_number')
    op.drop_column('profile', 'primary_phone_number')
    # ### end Alembic commands ###
