"""Updated driver table

Revision ID: 32818e172698
Revises: 25990eb36765
Create Date: 2025-10-23 17:11:40.412600

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '32818e172698'
down_revision = '25990eb36765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver', sa.Column('profile_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('driver_user_id_fkey'), 'driver', type_='foreignkey')
    op.create_foreign_key(None, 'driver', 'profile', ['profile_id'], ['id'])
    op.create_foreign_key(None, 'driver', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'driver', type_='foreignkey')
    op.drop_constraint(None, 'driver', type_='foreignkey')
    op.create_foreign_key(op.f('driver_user_id_fkey'), 'driver', 'profile', ['user_id'], ['id'])
    op.drop_column('driver', 'profile_id')
    # ### end Alembic commands ###
