"""Added created_at and update_at for all tables

Revision ID: 422f6ab1de6e
Revises: c877856d4d53
Create Date: 2025-11-02 02:22:16.976964

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '422f6ab1de6e'
down_revision = 'c877856d4d53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('booking', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='created_at::timestamp with time zone',
               server_default=sa.text("now()"),
               nullable=False)
    op.add_column('bookingcab', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('bookingcab', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='created_at::timestamp with time zone',
               server_default=sa.text("now()"),
               nullable=False)
    op.add_column('bookingstay', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('bookingstay', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='created_at::timestamp with time zone',
               server_default=sa.text("now()"),
               nullable=False)
    op.add_column('bookingtraveller', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('bookingtraveller', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('cab', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('cab', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('cabserviceprovider', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('cabserviceprovider', 'updated_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='updated_at::timestamp with time zone',
               server_default=sa.text("now()"),
               nullable=False)
    op.add_column('driver', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('driver', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('enquirydetails', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('enquirydetails', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='created_at::timestamp with time zone',
               server_default=sa.text("now()"),
               nullable=False)
    op.alter_column('note', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='created_at::timestamp with time zone',
               server_default=sa.text("now()"),
               nullable=False)
    op.alter_column('note', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='updated_at::timestamp with time zone',
               server_default=sa.text("now()"),
               nullable=False)
    op.add_column('phonenumber', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('phonenumber', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='created_at::timestamp with time zone',
               server_default=sa.text("now()"),
               nullable=False)
    op.alter_column('profile', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='created_at::timestamp with time zone',
               server_default=sa.text("now()"),
               nullable=False)
    op.alter_column('profile', 'updated_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='updated_at::timestamp with time zone',
               server_default=sa.text("now()"),
               nullable=False)
    op.add_column('serviceprovider', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('serviceprovider', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='created_at::timestamp with time zone',
               server_default=sa.text("now()"),
               nullable=False)
    op.add_column('stayamenity', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('stayamenity', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('stayserviceprovider', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('stayserviceprovider', 'updated_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='updated_at::timestamp with time zone',
               server_default=sa.text("now()"),
               nullable=False)
    op.add_column('stayunit', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('stayunit', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('travelagency', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('travelagency', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='created_at::timestamp with time zone',
               server_default=sa.text("now()"),
               nullable=False)
    op.alter_column('travelagencystaff', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='created_at::timestamp with time zone',
               server_default=sa.text("now()"),
               nullable=False)
    op.alter_column('travelagencystaff', 'updated_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='updated_at::timestamp with time zone',
               server_default=sa.text("now()"),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('travelagencystaff', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('travelagencystaff', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('travelagency', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               nullable=True)
    op.drop_column('travelagency', 'updated_at')
    op.drop_column('stayunit', 'updated_at')
    op.drop_column('stayunit', 'created_at')
    op.alter_column('stayserviceprovider', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               nullable=True)
    op.drop_column('stayserviceprovider', 'created_at')
    op.drop_column('stayamenity', 'updated_at')
    op.drop_column('stayamenity', 'created_at')
    op.alter_column('serviceprovider', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               nullable=True)
    op.drop_column('serviceprovider', 'updated_at')
    op.alter_column('profile', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('profile', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('phonenumber', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               nullable=True)
    op.drop_column('phonenumber', 'updated_at')
    op.alter_column('note', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('note', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('enquirydetails', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('enquirydetails', 'updated_at')
    op.drop_column('driver', 'updated_at')
    op.drop_column('driver', 'created_at')
    op.alter_column('cabserviceprovider', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               nullable=True)
    op.drop_column('cabserviceprovider', 'created_at')
    op.drop_column('cab', 'updated_at')
    op.drop_column('cab', 'created_at')
    op.drop_column('bookingtraveller', 'updated_at')
    op.drop_column('bookingtraveller', 'created_at')
    op.alter_column('bookingstay', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('bookingstay', 'updated_at')
    op.alter_column('bookingcab', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('bookingcab', 'updated_at')
    op.alter_column('booking', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('booking', 'updated_at')
    # ### end Alembic commands ###
