"""timestamp fields to user table

Revision ID: 51898cd753b2
Revises: 9de9ed6cebd7
Create Date: 2025-10-12 17:08:50.180224

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '51898cd753b2'
down_revision = '9de9ed6cebd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted to add timestamp columns ###
    # Add created_at and updated_at with server defaults (Postgres now())
    op.add_column(
        "user",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )

    op.add_column(
        "user",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )

    # NOTE: If you'd like updated_at to be database-updated on every UPDATE
    # (outside of ORM-managed updates), consider creating a DB trigger.
    # The SQLAlchemy `onupdate` is honored by the ORM when it issues updates.
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted to drop timestamp columns ###
    op.drop_column("user", "updated_at")
    op.drop_column("user", "created_at")

    # ### end Alembic commands ###
