"""updates on enquirydetails

Revision ID: 5861576c37eb
Revises: 422f6ab1de6e
Create Date: 2025-11-02 06:13:14.167809

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5861576c37eb'
down_revision = '422f6ab1de6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'enquirydetails', 'travelagencystaff', ['handled_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'enquirydetails', type_='foreignkey')
    # ### end Alembic commands ###
