"""make profile.user_id nullable

Revision ID: 5fcb8fb07604
Revises: replace_email_with_phone
Create Date: 2026-02-25 12:46:40.448844

This migration adjusts the `profile.user_id` column to allow NULL values
so that profiles can exist without being attached to a user record.  The
change is reversible in the downgrade, which sets the column back to
`nullable=False`.
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5fcb8fb07604'
down_revision = 'replace_email_with_phone'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile', 'user_id',
               existing_type=sa.Uuid(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile', 'user_id',
               existing_type=sa.Uuid(),
               nullable=False)
    # ### end Alembic commands ###