"""added from and to dates for booking model

Revision ID: 608369f9c2f8
Revises: 2e37a9d4b163
Create Date: 2026-06-26 03:55:06.192539

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '608369f9c2f8'
down_revision = '2e37a9d4b163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('date_starting_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('booking', sa.Column('date_ending_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('booking', 'booking_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('booking_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('booking', 'date_ending_on')
    op.drop_column('booking', 'date_starting_from')
    # ### end Alembic commands ###
