"""new feild for stayProviders - optimal_occupancy and max_occupancy

Revision ID: 6bded0749ba6
Revises: c051acfb399f
Create Date: 2026-03-26 15:45:41.351437

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6bded0749ba6'
down_revision = 'c051acfb399f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stayserviceprovider', sa.Column('optimal_occupancy', sa.Integer(), nullable=True))
    op.add_column('stayserviceprovider', sa.Column('max_occupancy', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stayserviceprovider', 'max_occupancy')
    op.drop_column('stayserviceprovider', 'optimal_occupancy')
    # ### end Alembic commands ###
