"""autogenerate travel models 2

Revision ID: 7f909e543305
Revises: 169c86e29223
Create Date: 2025-10-12 04:29:51.259582

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7f909e543305'
down_revision = '169c86e29223'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('serviceprovider',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider_type', sa.Enum('CAB', 'STAY', 'EXPERIENCE', 'ACTIVITY', 'DESTINATION', name='serviceprovidertype'), nullable=False),
    sa.Column('provider_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('travelagency',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agency_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cabserviceprovider',
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['serviceprovider.id'], ),
    sa.PrimaryKeyConstraint('provider_id')
    )
    op.create_table('enquirydetails',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('adult_men_count', sa.Integer(), nullable=True),
    sa.Column('adult_women_count', sa.Integer(), nullable=True),
    sa.Column('adult_no_binary_count', sa.Integer(), nullable=True),
    sa.Column('kids_below_12_boy_count', sa.Integer(), nullable=True),
    sa.Column('kids_below_12_girl_count', sa.Integer(), nullable=True),
    sa.Column('check_in', sa.DateTime(), nullable=True),
    sa.Column('check_out', sa.DateTime(), nullable=True),
    sa.Column('pickup_location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('drop_location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('handled_by', sa.Uuid(), nullable=True),
    sa.Column('enquired_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['enquired_by'], ['userprofile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phonenote',
    sa.Column('phone_id', sa.Uuid(), nullable=False),
    sa.Column('note_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], ),
    sa.ForeignKeyConstraint(['phone_id'], ['phonenumber.id'], ),
    sa.PrimaryKeyConstraint('phone_id', 'note_id')
    )
    op.create_table('profilenote',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('note_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['userprofile.id'], ),
    sa.PrimaryKeyConstraint('profile_id', 'note_id')
    )
    op.create_table('stayserviceprovider',
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('property_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('room_count', sa.Integer(), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['serviceprovider.id'], ),
    sa.PrimaryKeyConstraint('provider_id')
    )
    op.create_table('travelagencystaff',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('travel_agency_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('joined_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('resigned_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('resigning_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['travel_agency_id'], ['travelagency.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('traveler_id', sa.Uuid(), nullable=False),
    sa.Column('travel_agency_id', sa.Uuid(), nullable=True),
    sa.Column('travel_agency_staff_id', sa.Uuid(), nullable=True),
    sa.Column('enquiry_id', sa.Uuid(), nullable=True),
    sa.Column('booking_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', name='bookingstatus'), nullable=True),
    sa.Column('total_amount', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquirydetails.id'], ),
    sa.ForeignKeyConstraint(['travel_agency_id'], ['travelagency.id'], ),
    sa.ForeignKeyConstraint(['travel_agency_staff_id'], ['travelagencystaff.id'], ),
    sa.ForeignKeyConstraint(['traveler_id'], ['userprofile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cab',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_type', sa.Enum('SEDAN', 'SUV', 'HATCHBACK', 'VAN', name='vehicletype'), nullable=False),
    sa.Column('vehicle_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['cabserviceprovider.provider_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_number')
    )
    op.create_table('driver',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['cabserviceprovider.provider_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['userprofile.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('stayunit',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('room_rate', sa.Integer(), nullable=True),
    sa.Column('per_head_rate', sa.Integer(), nullable=True),
    sa.Column('max_occupancy', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['stayserviceprovider.provider_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookingcab',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cab_id', sa.Uuid(), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('cab_provider_id', sa.Uuid(), nullable=False),
    sa.Column('pickup_time', sa.DateTime(), nullable=True),
    sa.Column('pickup_location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('drop_time', sa.DateTime(), nullable=True),
    sa.Column('drop_location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('driver_id', sa.Uuid(), nullable=True),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', name='bookingstatus'), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.ForeignKeyConstraint(['cab_id'], ['cab.id'], ),
    sa.ForeignKeyConstraint(['cab_provider_id'], ['cabserviceprovider.provider_id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookingnote',
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('note_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], ),
    sa.PrimaryKeyConstraint('booking_id', 'note_id')
    )
    op.create_table('bookingstay',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stayunit_id', sa.Uuid(), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('stay_provider_id', sa.Uuid(), nullable=False),
    sa.Column('check_in', sa.DateTime(), nullable=True),
    sa.Column('check_out', sa.DateTime(), nullable=True),
    sa.Column('room_type', sa.Enum('SINGLE', 'DOUBLE', 'SUITE', 'DORM', name='roomtype'), nullable=True),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', name='bookingstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.ForeignKeyConstraint(['stay_provider_id'], ['stayserviceprovider.provider_id'], ),
    sa.ForeignKeyConstraint(['stayunit_id'], ['stayunit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookingtraveller',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('traveller_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.ForeignKeyConstraint(['traveller_id'], ['userprofile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stayamenity',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stay_service_provider_id', sa.Uuid(), nullable=False),
    sa.Column('stay_unit_id', sa.Uuid(), nullable=False),
    sa.Column('amenity_scope', sa.Enum('ROOM', 'COMMON', 'PRIVATE', name='amenityscope'), nullable=False),
    sa.Column('amenity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['stay_service_provider_id'], ['stayserviceprovider.provider_id'], ),
    sa.ForeignKeyConstraint(['stay_unit_id'], ['stayunit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stayamenity')
    op.drop_table('bookingtraveller')
    op.drop_table('bookingstay')
    op.drop_table('bookingnote')
    op.drop_table('bookingcab')
    op.drop_table('stayunit')
    op.drop_table('driver')
    op.drop_table('cab')
    op.drop_table('booking')
    op.drop_table('travelagencystaff')
    op.drop_table('stayserviceprovider')
    op.drop_table('profilenote')
    op.drop_table('phonenote')
    op.drop_table('enquirydetails')
    op.drop_table('cabserviceprovider')
    op.drop_table('travelagency')
    op.drop_table('serviceprovider')
    op.drop_table('note')
    op.drop_table('location')
    # ### end Alembic commands ###
