"""added missing timestamps in location

Revision ID: 85b963180f9a
Revises: 10f8e77f7eb3
Create Date: 2026-04-27 20:39:11.423992

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '85b963180f9a'
down_revision = '10f8e77f7eb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('location', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'updated_at')
    op.drop_column('location', 'created_at')
    # ### end Alembic commands ###
