"""Deleted UserProfile

Revision ID: 9de9ed6cebd7
Revises: 0f8d7d07c6ca
Create Date: 2025-10-12 16:33:13.526442

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9de9ed6cebd7'
down_revision = '0f8d7d07c6ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('middle_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('profile_picture', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('zip_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_user_id'), 'profile', ['user_id'], unique=False)
    # Replace foreign keys referencing old 'userprofile' to new 'profile'
    # booking.traveler_id -> profile.id
    try:
        op.drop_constraint(op.f('booking_traveler_id_fkey'), 'booking', type_='foreignkey')
    except Exception:
        pass
    op.create_foreign_key(None, 'booking', 'profile', ['traveler_id'], ['id'])

    # bookingtraveller.traveller_id -> profile.id
    try:
        op.drop_constraint(op.f('bookingtraveller_traveller_id_fkey'), 'bookingtraveller', type_='foreignkey')
    except Exception:
        pass
    op.create_foreign_key(None, 'bookingtraveller', 'profile', ['traveller_id'], ['id'])

    # driver.user_id -> profile.id
    try:
        op.drop_constraint(op.f('driver_user_id_fkey'), 'driver', type_='foreignkey')
    except Exception:
        pass
    op.create_foreign_key(None, 'driver', 'profile', ['user_id'], ['id'])

    # enquirydetails.enquired_by -> profile.id
    try:
        op.drop_constraint(op.f('enquirydetails_enquired_by_fkey'), 'enquirydetails', type_='foreignkey')
    except Exception:
        pass
    op.create_foreign_key(None, 'enquirydetails', 'profile', ['enquired_by'], ['id'])

    # profilenote.profile_id -> profile.id
    try:
        op.drop_constraint(op.f('profilenote_profile_id_fkey'), 'profilenote', type_='foreignkey')
    except Exception:
        pass
    op.create_foreign_key(None, 'profilenote', 'profile', ['profile_id'], ['id'])

    # alter phonenumber is_verified nullability (make non-nullable)
    op.alter_column('phonenumber', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # Now safe to drop the old userprofile table and its index
    try:
        op.drop_index(op.f('ix_userprofile_user_id'), table_name='userprofile')
    except Exception:
        pass
    try:
        op.drop_table('userprofile')
    except Exception:
        pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profilenote', type_='foreignkey')
    op.create_foreign_key(op.f('profilenote_profile_id_fkey'), 'profilenote', 'userprofile', ['profile_id'], ['id'])
    op.alter_column('phonenumber', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(None, 'enquirydetails', type_='foreignkey')
    op.create_foreign_key(op.f('enquirydetails_enquired_by_fkey'), 'enquirydetails', 'userprofile', ['enquired_by'], ['id'])
    op.drop_constraint(None, 'driver', type_='foreignkey')
    op.create_foreign_key(op.f('driver_user_id_fkey'), 'driver', 'userprofile', ['user_id'], ['id'])
    op.drop_constraint(None, 'bookingtraveller', type_='foreignkey')
    op.create_foreign_key(op.f('bookingtraveller_traveller_id_fkey'), 'bookingtraveller', 'userprofile', ['traveller_id'], ['id'])
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.create_foreign_key(op.f('booking_traveler_id_fkey'), 'booking', 'userprofile', ['traveler_id'], ['id'])
    op.create_table('userprofile',
    sa.Column('profile_picture', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('bio', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('zip_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('userprofile_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('userprofile_pkey'))
    )
    op.create_index(op.f('ix_userprofile_user_id'), 'userprofile', ['user_id'], unique=False)
    op.drop_index(op.f('ix_profile_user_id'), table_name='profile')
    op.drop_table('profile')
    # ### end Alembic commands ###
