"""added rates fields to Cab and StayUnit models

Revision ID: a92de890751c
Revises: 5861576c37eb
Create Date: 2025-12-30 08:46:38.878041

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a92de890751c'
down_revision = '5861576c37eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cab', sa.Column('minimum_rate', sa.Integer(), nullable=False))
    op.add_column('cab', sa.Column('km_for_minimum_rate', sa.Integer(), nullable=False))
    op.add_column('cab', sa.Column('per_km_rate', sa.Integer(), nullable=False))
    op.add_column('cab', sa.Column('capacity', sa.Integer(), nullable=False))
    op.add_column('cab', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('cab', sa.Column('company_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('cab', sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('stayunit', sa.Column('room_rate_occupancy', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stayunit', 'room_rate_occupancy')
    op.drop_column('cab', 'color')
    op.drop_column('cab', 'company_model')
    op.drop_column('cab', 'name')
    op.drop_column('cab', 'capacity')
    op.drop_column('cab', 'per_km_rate')
    op.drop_column('cab', 'km_for_minimum_rate')
    op.drop_column('cab', 'minimum_rate')
    # ### end Alembic commands ###
