"""new

Revision ID: c051acfb399f
Revises: 5fcb8fb07604
Create Date: 2026-02-27 17:49:36.178593

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c051acfb399f'
down_revision = '5fcb8fb07604'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # remove constraints to existing driver_pkey
    # bookingcab.driver_id -> driver.id
    try:
        op.drop_constraint(op.f('bookingcab_driver_id_fkey'), 'bookingcab', type_='foreignkey')
    except Exception:
        pass
    
    # Now safe to remove driver old primary key
    op.drop_constraint(op.f('driver_pkey'), 'driver')
    
    # make the driver id as new primary key
    op.create_primary_key(op.f('driver_pkey'), 'driver', ['id'])

    # assign bookingcab.driver_id -> driver.id
    op.create_foreign_key(None, 'bookingcab', 'driver', ['driver_id'], ['id'])

    # make the user_id nullable - which is previously drivers primary_key
    op.alter_column('driver', 'user_id',
               existing_type=sa.Uuid(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # remove constraints to new driver_pkey
    # bookingcab.driver_id -> driver.id
    try:
        op.drop_constraint(op.f('bookingcab_driver_id_fkey'), 'bookingcab', type_='foreignkey')
    except Exception:
        pass

    # Now safe to remove driver new primary key
    op.drop_constraint(op.f('driver_pkey'), 'driver')

    # make the driver user_id as old primary key
    op.create_primary_key(op.f('driver_pkey'), 'driver', ['user_id'])

    # make the user_id non-nullable - which is previously drivers primary_key
    op.alter_column('driver', 'user_id',
               existing_type=sa.Uuid(),
               nullable=False)

    # ### end Alembic commands ###
