"""fixed cab and driver table ids(fk)

Revision ID: c877856d4d53
Revises: 320b1617bac3
Create Date: 2025-10-24 17:59:25.026839

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c877856d4d53'
down_revision = '320b1617bac3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('driver', 'id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('driver', 'id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
