"""fields updates in Booking date and BookingCab notes

Revision ID: e8e409979e48
Revises: 2697aac7e31f
Create Date: 2026-05-22 14:04:00.148559

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e8e409979e48'
down_revision = '2697aac7e31f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking', 'booking_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.drop_column('bookingcab', 'notes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookingcab', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('booking', 'booking_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
