"""Added new models person and phonenumber

Revision ID: f1c1cb67d12d
Revises: a94ae91bbf12
Create Date: 2025-10-09 05:10:20.012529

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f1c1cb67d12d'
down_revision = 'a94ae91bbf12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('day_of_birth', sa.Integer(), nullable=True),
    sa.Column('month_of_birth', sa.Integer(), nullable=True),
    sa.Column('year_of_birth', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_email'), 'person', ['email'], unique=True)
    op.create_table('phonenumber',
    sa.Column('number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('person_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phonenumber_number'), 'phonenumber', ['number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phonenumber_number'), table_name='phonenumber')
    op.drop_table('phonenumber')
    op.drop_index(op.f('ix_person_email'), table_name='person')
    op.drop_table('person')
    # ### end Alembic commands ###
