"""Replace email with phone_number in user authentication

Revision ID: replace_email_with_phone
Revises: 26238344a724
Create Date: 2026-02-12 00:00:00.000000

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "replace_email_with_phone"
down_revision = "26238344a724"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop the unique index on email
    op.drop_index("ix_user_email", table_name="user")
    
    # Drop the email column
    op.drop_column("user", "email")
    
    # Add phone_number column with unique constraint
    op.add_column(
        "user",
        sa.Column(
            "phone_number",
            sqlmodel.sql.sqltypes.AutoString(length=20),
            nullable=False,
        ),
    )
    op.create_index(
        "ix_user_phone_number", "user", ["phone_number"], unique=True
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop the phone_number unique index
    op.drop_index("ix_user_phone_number", table_name="user")
    
    # Drop the phone_number column
    op.drop_column("user", "phone_number")
    
    # Re-add the email column with unique constraint
    op.add_column(
        "user",
        sa.Column(
            "email",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
    )
    op.create_index("ix_user_email", "user", ["email"], unique=True)
    
    # ### end Alembic commands ###
